import React, { useState } from 'react';
import { 
  Mail, 
  Send, 
  CheckCircle2, 
  ChevronDown,
  Clock,
  Sparkles
} from 'lucide-react';
import { Breadcrumbs } from '../shared/Breadcrumbs';
import { AdSlot } from '../shared/AdSlot';
import { useLanguage } from '../../i18n/LanguageContext';

interface ContactViewProps {
  onGoHome: () => void;
  onGoToAbout: () => void;
  onGoToBlog: () => void;
}

export const ContactView: React.FC<ContactViewProps> = ({
  onGoHome
}) => {
  const { t } = useLanguage();
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    topic: 'request_calculator',
    calculatorName: '',
    message: ''
  });
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.name || !formData.email || !formData.message) return;
    setIsSubmitted(true);
  };

  const handleReset = () => {
    setFormData({
      name: '',
      email: '',
      topic: 'request_calculator',
      calculatorName: '',
      message: ''
    });
    setIsSubmitted(false);
  };

  const contactFaqs = [
    {
      q: t('contact.faq1Q', 'How quickly do you implement newly requested calculators?'),
      a: t('contact.faq1A', 'Our mathematics engineering team reviews calculation requests weekly. High-demand financial, health, and engineering requests are typically prioritized and deployed within 7 to 14 business days.')
    },
    {
      q: t('contact.faq2Q', 'Are Calculio calculation engines free for commercial and classroom use?'),
      a: t('contact.faq2A', 'Yes, 100%. All calculators on Calculio are free for personal, educational, research, and commercial usage. You may link to our calculators or print reports without royalty fees.')
    },
    {
      q: t('contact.faq3Q', 'How do I report a mathematical bug or rounding edge-case?'),
      a: t('contact.faq3A', 'Select "Report a Calculation Bug" in the form above and provide the exact inputs, the output generated by our calculator, and your expected verified output. Our quantitative analysts audit and resolve reports within 24 hours.')
    },
    {
      q: t('contact.faq4Q', 'Can we license your calculation engine for white-label embedded use?'),
      a: t('contact.faq4A', 'Yes. Select "Partnership / API Inquiry" in the contact dropdown and our partnerships team will provide enterprise API documentation and widget embedding options.')
    }
  ];

  const breadcrumbs = [
    { label: t('contact.title', 'Contact & Calculator Requests'), active: true }
  ];

  return (
    <div className="min-h-screen bg-[#F8FAFC] py-8 sm:py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto space-y-10">
        
        {/* Breadcrumb Navigation */}
        <Breadcrumbs items={breadcrumbs} onGoHome={onGoHome} />

        {/* Hero Header */}
        <div className="bg-[#FFFFFF] text-[#0F172A] rounded-3xl p-8 sm:p-12 shadow-xs relative overflow-hidden space-y-4 border border-[#E2E8F0]">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#FFF7ED] text-[#9A3412] text-xs font-bold border border-[#FDBA74]">
            <Mail className="w-3.5 h-3.5 text-[#F97316]" />
            <span>{t('contact.badge', 'Community Feedback & Direct Support')}</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-black tracking-tight text-[#0F172A] leading-tight">
            {t('contact.headline', 'Get in Touch with Calculio')}
          </h1>

          <p className="text-sm sm:text-base text-[#475569] leading-relaxed max-w-2xl">
            {t('contact.subtitle', 'Have a question, feedback, or a suggestion for a new calculation engine? Our team of engineers and quantitative reviewers is here to help.')}
          </p>
        </div>

        {/* Header Ad Slot */}
        <AdSlot type="header-banner" />

        {/* Main Grid: Form + Contact Channels */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Contact Form (7 cols) */}
          <div className="lg:col-span-7 bg-[#FFFFFF] rounded-3xl p-6 sm:p-8 border border-[#E2E8F0] shadow-xs space-y-6">
            <div>
              <h2 className="text-xl font-bold text-[#0F172A]">{t('contact.formTitle', 'Send Us a Message')}</h2>
              <p className="text-xs text-[#64748B]">{t('contact.formSubtitle', 'We respond to all inquiries within 1 business day.')}</p>
            </div>

            {isSubmitted ? (
              <div className="p-8 rounded-2xl bg-[#FFF7ED] border border-[#FDBA74] text-center space-y-4 animate-fadeIn">
                <div className="w-14 h-14 bg-[#F97316] text-white rounded-2xl flex items-center justify-center mx-auto shadow-md">
                  <CheckCircle2 className="w-8 h-8" />
                </div>
                <div className="space-y-1">
                  <h3 className="text-lg font-bold text-[#0F172A]">
                    {t('contact.thankYou', 'Thank You, {name}!').replace('{name}', formData.name)}
                  </h3>
                  <p className="text-xs sm:text-sm text-[#9A3412] max-w-sm mx-auto">
                    {t('contact.receivedMessage', 'Your inquiry has been received by our editorial team.')}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={handleReset}
                  className="px-4 py-2 bg-[#F97316] hover:bg-[#EA580C] text-white text-xs font-bold rounded-xl transition-all shadow-xs cursor-pointer"
                >
                  {t('contact.sendAnother', 'Send Another Message')}
                </button>
              </div>
            ) : (
              <form onSubmit={handleSubmit} className="space-y-4">
                
                {/* Topic Selector */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-[#0F172A] block">
                    {t('contact.topicLabel', 'Inquiry Topic')} <span className="text-rose-500">*</span>
                  </label>
                  <select
                    value={formData.topic}
                    onChange={(e) => setFormData({ ...formData, topic: e.target.value })}
                    className="w-full text-xs font-semibold bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl px-3.5 py-2.5 text-[#0F172A] focus:outline-none focus:border-[#F97316]"
                  >
                    <option value="request_calculator">{t('contact.topicRequest', '✨ Suggest / Request a New Calculator')}</option>
                    <option value="bug_report">{t('contact.topicBug', '🐞 Report a Calculation Bug or Error')}</option>
                    <option value="editorial">{t('contact.topicEditorial', '✍️ Editorial or Formula Suggestion')}</option>
                    <option value="partnership">{t('contact.topicPartnership', '💼 Partnership or API Licensing')}</option>
                    <option value="general">{t('contact.topicGeneral', '💬 General Feedback or Question')}</option>
                  </select>
                </div>

                {/* Name & Email Row */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-[#0F172A] block">
                      {t('contact.nameLabel', 'Your Full Name')} <span className="text-rose-500">*</span>
                    </label>
                    <input
                      type="text"
                      required
                      placeholder="e.g. Alex Morgan"
                      value={formData.name}
                      onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                      className="w-full text-xs font-medium bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl px-3.5 py-2.5 text-[#0F172A] placeholder:text-[#94A3B8] focus:outline-none focus:border-[#F97316]"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-xs font-bold text-[#0F172A] block">
                      {t('contact.emailLabel', 'Your Email Address')} <span className="text-rose-500">*</span>
                    </label>
                    <input
                      type="email"
                      required
                      placeholder="e.g. alex@example.com"
                      value={formData.email}
                      onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                      className="w-full text-xs font-medium bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl px-3.5 py-2.5 text-[#0F172A] placeholder:text-[#94A3B8] focus:outline-none focus:border-[#F97316]"
                    />
                  </div>
                </div>

                {/* Specific Calculator Name (Optional) */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-[#0F172A] block">
                    {t('contact.calcNameLabel', 'Calculator Name or Topic (Optional)')}
                  </label>
                  <input
                    type="text"
                    placeholder="e.g. Roth IRA Conversion, Solar Panel ROI, Pregnancy Due Date"
                    value={formData.calculatorName}
                    onChange={(e) => setFormData({ ...formData, calculatorName: e.target.value })}
                    className="w-full text-xs font-medium bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl px-3.5 py-2.5 text-[#0F172A] placeholder:text-[#94A3B8] focus:outline-none focus:border-[#F97316]"
                  />
                </div>

                {/* Message */}
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-[#0F172A] block">
                    {t('contact.messageLabel', 'Message Details')} <span className="text-rose-500">*</span>
                  </label>
                  <textarea
                    required
                    rows={5}
                    placeholder={t('contact.messagePlaceholder', 'Please explain the calculator you would like to see, or provide the exact formula, inputs, and desired features...')}
                    value={formData.message}
                    onChange={(e) => setFormData({ ...formData, message: e.target.value })}
                    className="w-full text-xs font-medium bg-[#F8FAFC] border border-[#E2E8F0] rounded-xl p-3.5 text-[#0F172A] placeholder:text-[#94A3B8] focus:outline-none focus:border-[#F97316]"
                  />
                </div>

                {/* Submit Button */}
                <button
                  type="submit"
                  className="w-full py-3 bg-[#F97316] hover:bg-[#EA580C] text-white font-bold text-xs rounded-xl shadow-md transition-all flex items-center justify-center gap-2 active:scale-95 cursor-pointer"
                >
                  <Send className="w-4 h-4" />
                  <span>{t('contact.submitButton', 'Submit Inquiry')}</span>
                </button>
              </form>
            )}
          </div>

          {/* Right Info Cards (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* Quick Contact Info */}
            <div className="p-6 rounded-3xl bg-[#FFFFFF] border border-[#E2E8F0] shadow-xs space-y-4">
              <span className="text-xs font-bold uppercase tracking-wider text-[#F97316] block">
                {t('contact.channelsTitle', 'Direct Contact Channels')}
              </span>

              <div className="space-y-3">
                <div className="p-3.5 rounded-2xl bg-[#F8FAFC] border border-[#E2E8F0] flex items-start gap-3">
                  <Mail className="w-5 h-5 text-[#F97316] shrink-0 mt-0.5" />
                  <div>
                    <span className="text-xs font-bold text-[#0F172A] block">{t('contact.editorialChannel', 'Direct Contact & Editorial')}</span>
                    <a href="mailto:contact@calculio.site" className="text-xs text-[#F97316] font-semibold hover:underline">
                      contact@calculio.site
                    </a>
                  </div>
                </div>

                <div className="p-3.5 rounded-2xl bg-[#F8FAFC] border border-[#E2E8F0] flex items-start gap-3">
                  <Clock className="w-5 h-5 text-[#F97316] shrink-0 mt-0.5" />
                  <div>
                    <span className="text-xs font-bold text-[#0F172A] block">{t('contact.responseChannel', 'Response Standard')}</span>
                    <span className="text-xs text-[#475569]">{t('contact.responseTime', 'Within 24 business hours')}</span>
                  </div>
                </div>

                <div className="p-3.5 rounded-2xl bg-[#F8FAFC] border border-[#E2E8F0] flex items-start gap-3">
                  <Sparkles className="w-5 h-5 text-[#F97316] shrink-0 mt-0.5" />
                  <div>
                    <span className="text-xs font-bold text-[#0F172A] block">{t('contact.velocityChannel', 'Feature Velocity')}</span>
                    <span className="text-xs text-[#475569]">{t('contact.velocityTime', '3-5 new tools added every release cycle')}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Sidebar Ad Placement */}
            <AdSlot type="sidebar" />

          </div>

        </div>

        {/* Contact FAQ Accordion */}
        <div className="p-8 rounded-3xl bg-[#FFFFFF] border border-[#E2E8F0] shadow-xs space-y-6">
          <div className="space-y-1">
            <h3 className="text-xl font-bold text-[#0F172A]">{t('contact.faqHeading', 'Common Support Inquiries')}</h3>
            <p className="text-xs text-[#64748B]">{t('contact.faqSubheading', 'Quick answers to frequently asked questions regarding Calculio.')}</p>
          </div>

          <div className="divide-y divide-[#E2E8F0]">
            {contactFaqs.map((item, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="py-3.5">
                  <button
                    type="button"
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="w-full flex items-center justify-between text-left gap-4 font-bold text-xs sm:text-sm text-[#0F172A] hover:text-[#F97316] transition-colors cursor-pointer"
                  >
                    <span>{item.q}</span>
                    <ChevronDown className={`w-4 h-4 text-[#64748B] transition-transform ${isOpen ? 'rotate-180 text-[#F97316]' : ''}`} />
                  </button>
                  {isOpen && (
                    <div className="mt-2 text-xs sm:text-sm text-[#475569] leading-relaxed animate-fadeIn">
                      {item.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

      </div>
    </div>
  );
};
